# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- xcodebuild -workspace Example/MVUIHacks.xcworkspace -scheme MVUIHacks #builds framework 
- xcodebuild CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -workspace Example/MVUIHacks.xcworkspace -scheme MVUIHacks-Example #builds example project
